services:
  app:
    image: ghcr.io/hrnco/http2tcp-signing-server:latest
#    build:
#      context: .
#      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    environment:
      APP_ENV: dev
    volumes:
      - .:/var/www/html
      - keys:/keys
volumes:
  keys:
