services:
  app:
    image: ghcr.io/hrnco/http2tcp-signing-server:latest
#    build:
#      context: .
#      dockerfile: .docker/Dockerfile
    ports:
      - "8080:80"
    environment:
      APP_ENV: dev
      TEST_DEFAULT_DEVICE_PORT: 9000
      TEST_DEFAULT_DEVICE_IP: tcp-echo
      TEST_DEFAULT_DEVICE_MODEL: echo-test
    volumes:
      - .:/var/www/html
      - keys:/keys
volumes:
  keys:
